"""Regex-based parser for mbn.co.kr section list pages (``/news/{section}/``).

The list page markup fails BeautifulSoup tree parsing for a *different*
reason than the article-detail pages (unbalanced ``<script>``/comment
constructs inside the listing widgets rather than the GTM iframe bug) — see
the crawl-phase investigation notes. Direct extraction is used deliberately
instead of chasing that breakage.

This module also loads the already-produced index survey JSON that was
generated by the prototype crawler (``crawl/mbn_label_survey.py``, outside
this repo) so notebook 02a can validate it without re-crawling.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

INDEX_PARSER_VERSION = "mbn_index_parser@1"

# Matches <dt class="tit"><a href="...ID">TITLE</a></dt> ... <span class="date">DATE</span>
_LIST_ITEM_RE = re.compile(
    r'<dt class="tit"><a href="[^"]*?(\d{6,8})">(.*?)</a></dt>.*?<span class="date">([\d\- :]+)</span>',
    re.DOTALL,
)
# Leading [Label] only — trailing [SourceOutlet] attribution tags are excluded by construction.
LABEL_PATTERN = re.compile(r"^\s*\[([^\[\]]+)\]")


def parse_list_page(html: str) -> list[dict[str, str]]:
    items = []
    for art_id, title, date in _LIST_ITEM_RE.findall(html):
        title = re.sub(r"\s+", " ", title).strip()
        items.append({"id": art_id, "title": title, "date": date.strip()})
    return items


def extract_bracket_label(raw_title: str) -> str | None:
    m = LABEL_PATTERN.match(raw_title)
    return m.group(1).strip() if m else None


def load_source_survey_json(path: Path) -> dict[str, Any]:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def survey_articles_to_index_records(
    survey: dict[str, Any],
    *,
    source: str,
    section: str,
    collected_at: str,
    raw_sha256: str,
) -> list[dict[str, Any]]:
    """Map the prototype survey JSON's ``articles`` list to the article_index contract."""
    records = []
    for row in survey["articles"]:
        article_id = str(row["id"])
        records.append(
            {
                "articleId": article_id,
                "source": source,
                "sourceArticleId": article_id,
                "url": row["url"],
                "rawTitle": row["title"],
                "publishedAt": row["date"],
                "section": section,
                "collectedAt": collected_at,
                "rawSha256": raw_sha256,
                "indexParserVersion": INDEX_PARSER_VERSION,
                "hasBracketLabel": extract_bracket_label(row["title"]) is not None,
            }
        )
    return records
