import type { Locale } from '../../shared/i18n'

export type MessageCatalog = Record<string, string>

export const messages: Record<Locale, MessageCatalog> = {
  ko: {
    'foundation.title': '프런트엔드 기반', 'foundation.description': '제품 계약을 소비하기 전의 중립 런타임 상태입니다.', 'foundation.status.title': '기반 준비됨', 'foundation.status.description': '공용 UI, 접근성, 언어 전환 및 상태 기반을 점검할 수 있습니다.', 'foundation.openOverlay': '오버레이 열기', 'foundation.showToast': '알림 표시', 'foundation.toast': '공용 알림이 표시되었습니다.', 'foundation.locale': '언어', 'foundation.overlay.title': '접근 가능한 오버레이', 'foundation.overlay.description': 'Escape 키 또는 닫기 동작으로 이 레이어를 종료할 수 있습니다.', 'foundation.overlay.close': '닫기',
    'common.back': '뒤로', 'common.openDetail': '상세 보기', 'common.openStory': '스토리 보기', 'common.openSession': '세션 보기', 'common.openPlace': '장소 보기', 'common.language': '언어', 'common.saved': '저장됨', 'common.save': '저장', 'common.removeSaved': '저장 해제', 'common.share': '공유',
    'nav.primary': '주요 탐색', 'nav.utility': '보조 메뉴', 'nav.guide': '가이드', 'nav.discover': '발견', 'nav.live': '라이브', 'nav.search': '검색', 'nav.saved': '저장됨', 'nav.settings': '설정',
    'guide.title': '맥락을 담은 문화', 'guide.description': 'fixture 전용 발견 화면입니다. 이 화면은 실시간 가능 여부나 출처가 있는 추천을 의미하지 않습니다.', 'guide.mapUnavailableTitle': '지도 공급자가 연결되지 않았습니다', 'guide.mapUnavailableDescription': '목록 대체 화면이 활성화되어 있습니다. 이 빌드에서는 지도 SDK, 지오코딩, 거리 계산을 실행하지 않습니다.', 'guide.filters': '문화 카테고리 필터', 'guide.all': '전체', 'guide.noMatches': '이 필터와 일치하는 fixture가 없습니다.', 'guide.noMatchesDescription': '이는 오류가 아닌 명시적 빈 결과입니다.', 'guide.fixtureActive': 'Fixture 활성', 'guide.unavailable': '이용 불가', 'guide.whyItMatters': '왜 중요한가',
    'discover.title': '에디토리얼 맥락', 'discover.description': 'Fixture 전용 콘텐츠입니다. 승인된 projection이 생길 때까지 Community는 이용 불가로 관리됩니다.', 'discover.view': '발견 보기', 'discover.magazine': '매거진', 'discover.community': '커뮤니티', 'discover.communityUnavailableTitle': '커뮤니티 projection을 사용할 수 없습니다', 'discover.communityUnavailableDescription': '쓰기 피드, 참가자 정체성, 활동 수, moderation 상태를 시뮬레이션하지 않습니다.', 'discover.noCommunityTitle': '관리된 CommunityPost fixture 없음', 'discover.noCommunityDescription': '성공적인 소셜 피드처럼 표시하지 않습니다.', 'discover.noStoriesTitle': '스토리 projection 없음', 'discover.noStoriesDescription': '이 릴리스에는 에디토리얼 fixture가 없습니다.',
    'live.noSessionsTitle': '세션 projection 없음', 'live.noSessionsDescription': '이 릴리스에는 라이브 fixture가 없습니다.', 'live.fixtureHub': '라이브 fixture 허브', 'live.noProviderTitle': '라이브 공급자가 연결되지 않았습니다', 'live.noProviderDescription': '세션 카드는 선언된 fixture 상태만 표시합니다.',
    'place.noStoryTitle': '연결된 스토리 projection 없음', 'place.noStoryDescription': '이 fixture는 에디토리얼 관계를 임의로 만들지 않습니다.', 'place.communityTitle': '커뮤니티 콘텐츠 이용 불가', 'place.communityDescription': '공개 활동이나 참여자 수를 시뮬레이션하지 않습니다.', 'place.offerTitle': '연결된 유효 Offer가 없습니다', 'place.offerDescription': '결제, 예약, 할인, 재고, 파트너 행동을 표시하지 않습니다.', 'place.actions': '장소 행동',
    'place.back': '← 가이드로 돌아가기', 'place.why': '왜 중요한가', 'place.experience': '현재 가능한 경험', 'place.editorial': '관련 에디토리얼 맥락', 'place.community': '커뮤니티 근거', 'place.offer': 'Offer 및 파트너 행동',
    'story.back': '← 발견으로 돌아가기', 'story.unavailable': '이 스토리를 사용할 수 없습니다.', 'story.video': '영상 맥락', 'story.videoUnavailableTitle': '승인된 미디어 projection 없음', 'story.videoUnavailableDescription': '이 fixture는 재생 가능한 플레이어나 방송을 의미하지 않습니다.', 'story.relatedPlaces': '관련 장소', 'story.noRelatedPlace': '관련 장소 없음',
    'live.back': '← 라이브로 돌아가기', 'live.unavailable': '이 세션을 사용할 수 없습니다.', 'live.player': '플레이어', 'live.playerAvailable': '플레이어 사용 가능', 'live.playerUnavailable': '플레이어 사용 불가', 'live.playerUnavailableDescription': '이 fixture는 미디어를 렌더링하지 않습니다.', 'live.chat': '채팅 및 반응', 'live.chatAvailable': '채팅 사용 가능', 'live.chatUnavailable': '채팅 사용 불가', 'live.chatUnavailableDescription': '참가자, 시청자, 반응 수를 임의로 만들지 않습니다.', 'live.relatedPlace': '관련 장소', 'live.noRelatedPlace': '관련 장소 없음', 'live.offer': 'Offer 및 파트너 행동', 'live.noOffer': '유효 Offer가 연결되지 않았습니다', 'live.noOfferDescription': '파트너 CTA를 표시하지 않습니다.',
    'saved.updateFailed': '이 기기에서 저장 항목을 갱신할 수 없습니다.', 'saved.saved': '이 기기에 저장했습니다.', 'saved.removed': '저장 목록에서 제거했습니다.', 'share.copied': '링크를 복사했습니다.', 'share.unavailable': '이 기기에서는 공유를 사용할 수 없습니다.', 'share.failed': '공유를 완료하지 못했습니다.',
    'status.fixtureOnly': '데모 릴리스 — 실증 데이터 아님', 'status.fixtureOnlyDescription': 'PY 릴리스를 소비하지 않습니다.',
  },
  en: {
    'foundation.title': 'Frontend foundation', 'foundation.description': 'A neutral runtime state before a product contract is consumed.', 'foundation.status.title': 'Foundation ready', 'foundation.status.description': 'Shared UI, accessibility, locale switching, and state infrastructure are available.', 'foundation.openOverlay': 'Open overlay', 'foundation.showToast': 'Show notification', 'foundation.toast': 'A shared notification is now visible.', 'foundation.locale': 'Language', 'foundation.overlay.title': 'Accessible overlay', 'foundation.overlay.description': 'Use Escape or the close action to leave this layer.', 'foundation.overlay.close': 'Close',
    'common.back': 'Back', 'common.openDetail': 'Open detail', 'common.openStory': 'Open Story', 'common.openSession': 'Open session', 'common.openPlace': 'Open place', 'common.language': 'Language', 'common.saved': 'Saved', 'common.save': 'Save', 'common.removeSaved': 'Remove saved', 'common.share': 'Share',
    'nav.primary': 'Primary navigation', 'nav.utility': 'Utility navigation', 'nav.guide': 'GUIDE', 'nav.discover': 'DISCOVER', 'nav.live': 'LIVE', 'nav.search': 'Search', 'nav.saved': 'Saved', 'nav.settings': 'Settings',
    'guide.title': 'Culture, with context', 'guide.description': 'Fixture-only discovery. This screen does not represent live availability or sourced recommendations.', 'guide.mapUnavailableTitle': 'Map provider is not connected', 'guide.mapUnavailableDescription': 'List fallback is active. No map SDK, geocoding, or distance calculation is running in this build.', 'guide.filters': 'Culture category filters', 'guide.all': 'All', 'guide.noMatches': 'No fixture matches this filter.', 'guide.noMatchesDescription': 'This is an explicit empty result, not an error.', 'guide.fixtureActive': 'Fixture active', 'guide.unavailable': 'Unavailable', 'guide.whyItMatters': 'Why it matters',
    'discover.title': 'Editorial context', 'discover.description': 'Fixture-only content. Community is governed as unavailable until an approved projection exists.', 'discover.view': 'Discover view', 'discover.magazine': 'Magazine', 'discover.community': 'Community', 'discover.communityUnavailableTitle': 'Community projection unavailable', 'discover.communityUnavailableDescription': 'No writable feed, participant identity, activity count, or moderation status is simulated.', 'discover.noCommunityTitle': 'No governed CommunityPost fixture', 'discover.noCommunityDescription': 'This is not shown as a successful social feed.', 'discover.noStoriesTitle': 'No Story projection', 'discover.noStoriesDescription': 'No editorial fixture is available in this release.',
    'live.noSessionsTitle': 'No session projection', 'live.noSessionsDescription': 'No live fixture is available in this release.', 'live.fixtureHub': 'Live fixture hub', 'live.noProviderTitle': 'No live provider is connected', 'live.noProviderDescription': 'Session cards expose only declared fixture status.',
    'place.noStoryTitle': 'No linked Story projection', 'place.noStoryDescription': 'This fixture does not invent an editorial relation.', 'place.communityTitle': 'Community content unavailable', 'place.communityDescription': 'No public activity or participant count is simulated.', 'place.offerTitle': 'No eligible offer is connected', 'place.offerDescription': 'No checkout, reservation, discount, inventory, or partner action is shown.', 'place.actions': 'Place actions',
    'place.back': '← Back to GUIDE', 'place.why': 'Why it matters', 'place.experience': 'Available experience', 'place.editorial': 'Related editorial context', 'place.community': 'Community evidence', 'place.offer': 'Offer and partner action',
    'story.back': '← Back to DISCOVER', 'story.unavailable': 'This Story is unavailable.', 'story.video': 'Video context', 'story.videoUnavailableTitle': 'No approved media projection', 'story.videoUnavailableDescription': 'This fixture does not imply an available player or broadcast.', 'story.relatedPlaces': 'Related places', 'story.noRelatedPlace': 'No related Place',
    'live.back': '← Back to LIVE', 'live.unavailable': 'This session is unavailable.', 'live.player': 'Player', 'live.playerAvailable': 'Player available', 'live.playerUnavailable': 'Player unavailable', 'live.playerUnavailableDescription': 'This fixture does not render media.', 'live.chat': 'Chat and reactions', 'live.chatAvailable': 'Chat available', 'live.chatUnavailable': 'Chat unavailable', 'live.chatUnavailableDescription': 'No participant, viewer, or reaction count is fabricated.', 'live.relatedPlace': 'Related place', 'live.noRelatedPlace': 'No related Place', 'live.offer': 'Offer and partner action', 'live.noOffer': 'No eligible offer is connected', 'live.noOfferDescription': 'No partner CTA is displayed.',
    'saved.updateFailed': 'Unable to update saved items on this device.', 'saved.saved': 'Saved on this device.', 'saved.removed': 'Removed from saved items.', 'share.copied': 'Link copied.', 'share.unavailable': 'Sharing is unavailable on this device.', 'share.failed': 'Sharing could not be completed.',
    'status.fixtureOnly': 'Demo release — not empirical data', 'status.fixtureOnlyDescription': 'No PY release is consumed.',
  },
}
